// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDARAJjOynWqBCS_VQoh4Mvgh79BvU9oD0',
    appId: '1:257756705217:web:f4d211bfc6672fc1de7f40',
    messagingSenderId: '257756705217',
    projectId: 'frosh-app24',
    authDomain: 'frosh-app24.firebaseapp.com',
    storageBucket: 'frosh-app24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWMnruxgQTRDHvqA398c-pjiy4JOUPIdw',
    appId: '1:257756705217:android:faa396ba88682081de7f40',
    messagingSenderId: '257756705217',
    projectId: 'frosh-app24',
    storageBucket: 'frosh-app24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDB5ioaUpwAyRFwl-dZ4hoRcgMb93MIe0',
    appId: '1:257756705217:ios:1147c0879edecc0cde7f40',
    messagingSenderId: '257756705217',
    projectId: 'frosh-app24',
    storageBucket: 'frosh-app24.appspot.com',
    iosBundleId: 'com.example.froshapp67',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDB5ioaUpwAyRFwl-dZ4hoRcgMb93MIe0',
    appId: '1:257756705217:ios:df131c9ff7449489de7f40',
    messagingSenderId: '257756705217',
    projectId: 'frosh-app24',
    storageBucket: 'frosh-app24.appspot.com',
    iosBundleId: 'com.example.froshapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDARAJjOynWqBCS_VQoh4Mvgh79BvU9oD0',
    appId: '1:257756705217:web:171a843ef6a6d442de7f40',
    messagingSenderId: '257756705217',
    projectId: 'frosh-app24',
    authDomain: 'frosh-app24.firebaseapp.com',
    storageBucket: 'frosh-app24.appspot.com',
  );
}
